### PR TITLE
add toc

### PR DESCRIPTION
**Pull request by stoeffel**
What do you think about adding a TOC to have a quick overview over the topics?

### CODE REVIEW

**Comment by hemanth** [comment]
Heh heh neat. :)

**Comment by hemanth** [comment]
@stoeffel Checkout #6 If you few more feel free to add :)

**Comment by stoeffel** [comment]
Sure, I will add more :smile:

**Comment by hemanth** [comment]
@stoeffel You might like [paws-on-es6](https://github.com/hemanth/paws-on-es6) ;)

**Pull request merged**
