### PR TITLE
add links to coffeescript doc

### PR DESCRIPTION
**Pull request by stoeffel**
I think would be nice to have links to the corresponding topic in the coffeescript documentation.

### CODE REVIEW

**Comment by hemanth** [comment]
If this goes in, then we must also link to relevant ES6 specs?

**Comment by stoeffel** [comment]
Yes, we could add two icons next to the title (a svg logo of cs and es6). I will create a proposal tomorrow if you like the idea.

**Comment by hemanth** [comment]
@stoeffel Sure, awesome!

Do also make a contributors list and add yourself to it please :)

**Comment by stoeffel** [comment]
@hemanth I added the links to the coffeescript/es6 documentation and a contributors list.
:sparkles: Thanks :sparkles:

**Comment by hemanth** [comment]
@stoeffel Awesomeness! :100:

**Comment by hemanth** [comment]
@stoeffel Should we use different icons of each of them? Say like :book: and :page_facing_up: or is it an overkill?

**Comment by stoeffel** [comment]
@hemanth how about using the language icons? https://github.com/stoeffel/coffeescript-equivalents-in-es6/tree/nice-icons

**Pull request merged**
